
/*


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer:
	4613732
*/

#include <iostream>
#include <array>

int main()
{
    unsigned long number = 0;
    unsigned long num1 = 1, num2 = 2;
    unsigned long sum = 0;
    while (1)
    {

        number = num1 + num2;
        if (number <= 4000000)
        {
            std::cout << number << ' ';
            if (number % 2 == 0)
                sum += number;
        }
        else
        {
            break;
        }
        num1 = num2;
        num2 = number;
    }
    std::cout << '\n'
              << "sum is:" << sum + 2 << std::endl;
}