/*
Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
answer:76576500
*/
#include <iostream>
#include <cmath>
int main()
{
    //calculate triangular number
    int triangular_number = 0;
    int i = 1;
    while (1)
    {
        int divisor_count = 0;
        triangular_number += i++;
        std::cout << triangular_number << std::endl;
        for (int i = 1; i <= sqrt(triangular_number); i++)
        {
            if ((triangular_number % i) == 0)
            {
                if (triangular_number / i == i)
                    ++divisor_count;
                else
                    divisor_count += 2;
            }
        }
        std::cout << "divisible count:" << divisor_count << std::endl;
        if (divisor_count >= 500)
            break;
    }
    std::cout << triangular_number << std::endl;
}